// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_qeAIslNTn-HodEBBQ45ei3R_mHgtR3c',
    appId: '1:68531909630:web:9af96bb4e87e1869bac6af',
    messagingSenderId: '68531909630',
    projectId: 'dorianapp-62b8f',
    authDomain: 'dorianapp-62b8f.firebaseapp.com',
    storageBucket: 'dorianapp-62b8f.appspot.com',
    measurementId: 'G-VD2TW4VW57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARtRDsY6eyytcbUNM2GEJtr2ocLYA1xlI',
    appId: '1:68531909630:android:7aacdd1bde53adc3bac6af',
    messagingSenderId: '68531909630',
    projectId: 'dorianapp-62b8f',
    storageBucket: 'dorianapp-62b8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvlWhQ74PQBVca_ozqyWVwFatrs5Sr_Ks',
    appId: '1:68531909630:ios:8e7e56b929589f77bac6af',
    messagingSenderId: '68531909630',
    projectId: 'dorianapp-62b8f',
    storageBucket: 'dorianapp-62b8f.appspot.com',
    iosBundleId: 'com.example.flutterTestApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvlWhQ74PQBVca_ozqyWVwFatrs5Sr_Ks',
    appId: '1:68531909630:ios:55299b9623116db1bac6af',
    messagingSenderId: '68531909630',
    projectId: 'dorianapp-62b8f',
    storageBucket: 'dorianapp-62b8f.appspot.com',
    iosBundleId: 'com.example.flutterTestApplication1.RunnerTests',
  );
}
